"""initial mvp schema

Revision ID: 267e4ded3dc6
Revises: 
Create Date: 2026-09-05 09:38:02.997681
"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


revision: str = '267e4ded3dc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('account_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('profile_is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_account_status'), 'profiles', ['account_status'], unique=False)
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), server_default='ANDROID', nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('os_version', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=128), nullable=True),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_devices_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_fingerprint_hash'), 'devices', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('leaderboard_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=100), server_default='global', nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_leaderboard_scores_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_scores')),
    sa.UniqueConstraint('user_id', 'scope', 'scope_key', 'category', 'period_start', name='leaderboard_entry')
    )
    op.create_index('ix_leaderboard_rank_lookup', 'leaderboard_scores', ['scope', 'scope_key', 'category', 'period_start', 'score'], unique=False)
    op.create_index(op.f('ix_leaderboard_scores_user_id'), 'leaderboard_scores', ['user_id'], unique=False)
    op.create_table('player_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fitness_xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_qualifying_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_player_progress_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_player_progress'))
    )
    op.create_table('territories',
    sa.Column('cell_id', sa.String(length=16), nullable=False),
    sa.Column('h3_resolution', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('previous_owner_id', sa.UUID(), nullable=True),
    sa.Column('base_power', sa.Numeric(precision=6, scale=2), server_default='100', nullable=False),
    sa.Column('power_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_defended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_visitor_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('territory_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('base_power >= 0 AND base_power <= 100', name=op.f('ck_territories_power_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_territories_owner_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cell_id', name=op.f('pk_territories'))
    )
    op.create_index(op.f('ix_territories_h3_resolution'), 'territories', ['h3_resolution'], unique=False)
    op.create_index(op.f('ix_territories_owner_id'), 'territories', ['owner_id'], unique=False)
    op.create_index('ix_territories_owner_power', 'territories', ['owner_id', 'base_power'], unique=False)
    op.create_table('xp_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('rules_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_xp_ledger_positive_amount')),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_xp_ledger_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_ledger')),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', name='xp_source_once')
    )
    op.create_index(op.f('ix_xp_ledger_user_id'), 'xp_ledger', ['user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='STARTED', nullable=False),
    sa.Column('server_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('moving_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('average_speed_mps', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('calories_kcal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('route', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('competitive_eligible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rules_version', sa.String(length=30), server_default='mvp-v1', nullable=False),
    sa.Column('session_nonce_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('distance_meters >= 0', name=op.f('ck_runs_distance_non_negative')),
    sa.CheckConstraint('moving_seconds >= 0', name=op.f('ck_runs_moving_time_non_negative')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_runs_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_runs_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('session_nonce_hash', name=op.f('uq_runs_session_nonce_hash'))
    )
    op.create_index(op.f('ix_runs_device_id'), 'runs', ['device_id'], unique=False)
    op.create_index(op.f('ix_runs_finished_at'), 'runs', ['finished_at'], unique=False)
    op.create_index('ix_runs_route_gist', 'runs', ['route'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_runs_server_started_at'), 'runs', ['server_started_at'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_runs_validation_status'), 'runs', ['validation_status'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('client_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_events_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('run_id', 'sequence', name='run_event_sequence')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('run_gps_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('client_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=False),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('h3_cell_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_gps_points_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_gps_points')),
    sa.UniqueConstraint('run_id', 'sequence', name='run_gps_point_sequence')
    )
    op.create_index(op.f('ix_run_gps_points_h3_cell_id'), 'run_gps_points', ['h3_cell_id'], unique=False)
    op.create_index('ix_run_gps_points_position_gist', 'run_gps_points', ['position'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_run_gps_points_run_id'), 'run_gps_points', ['run_id'], unique=False)
    op.create_index('ix_run_gps_points_run_recorded', 'run_gps_points', ['run_id', 'client_recorded_at'], unique=False)
    op.create_table('run_sensor_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=True),
    sa.Column('activity_confidence', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_sensor_segments_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_sensor_segments')),
    sa.UniqueConstraint('run_id', 'sequence', name='run_sensor_segment_sequence')
    )
    op.create_index(op.f('ix_run_sensor_segments_run_id'), 'run_sensor_segments', ['run_id'], unique=False)
    op.create_table('run_upload_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('first_sequence', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_upload_batches_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_upload_batches')),
    sa.UniqueConstraint('run_id', 'batch_id', name='run_upload_batch_id')
    )
    op.create_index(op.f('ix_run_upload_batches_run_id'), 'run_upload_batches', ['run_id'], unique=False)
    op.create_table('run_validations',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('gps_score', sa.Integer(), nullable=False),
    sa.Column('motion_score', sa.Integer(), nullable=False),
    sa.Column('activity_score', sa.Integer(), nullable=False),
    sa.Column('route_score', sa.Integer(), nullable=False),
    sa.Column('device_score', sa.Integer(), nullable=False),
    sa.Column('final_trust_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_validations_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run_validations'))
    )
    op.create_index(op.f('ix_run_validations_final_trust_score'), 'run_validations', ['final_trust_score'], unique=False)
    op.create_index(op.f('ix_run_validations_status'), 'run_validations', ['status'], unique=False)
    op.create_table('territory_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('previous_owner_id', sa.UUID(), nullable=True),
    sa.Column('new_owner_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('power_before', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('power_after', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rules_version', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['profiles.id'], name=op.f('fk_territory_events_actor_user_id_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cell_id'], ['territories.cell_id'], name=op.f('fk_territory_events_cell_id_territories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_territory_events_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_territory_events'))
    )
    op.create_index(op.f('ix_territory_events_action_type'), 'territory_events', ['action_type'], unique=False)
    op.create_index(op.f('ix_territory_events_actor_user_id'), 'territory_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_territory_events_cell_id'), 'territory_events', ['cell_id'], unique=False)
    op.create_index('ix_territory_events_cell_time', 'territory_events', ['cell_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_territory_events_run_id'), 'territory_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_territory_events_run_id'), table_name='territory_events')
    op.drop_index('ix_territory_events_cell_time', table_name='territory_events')
    op.drop_index(op.f('ix_territory_events_cell_id'), table_name='territory_events')
    op.drop_index(op.f('ix_territory_events_actor_user_id'), table_name='territory_events')
    op.drop_index(op.f('ix_territory_events_action_type'), table_name='territory_events')
    op.drop_table('territory_events')
    op.drop_index(op.f('ix_run_validations_status'), table_name='run_validations')
    op.drop_index(op.f('ix_run_validations_final_trust_score'), table_name='run_validations')
    op.drop_table('run_validations')
    op.drop_index(op.f('ix_run_upload_batches_run_id'), table_name='run_upload_batches')
    op.drop_table('run_upload_batches')
    op.drop_index(op.f('ix_run_sensor_segments_run_id'), table_name='run_sensor_segments')
    op.drop_table('run_sensor_segments')
    op.drop_index('ix_run_gps_points_run_recorded', table_name='run_gps_points')
    op.drop_index(op.f('ix_run_gps_points_run_id'), table_name='run_gps_points')
    op.drop_index('ix_run_gps_points_position_gist', table_name='run_gps_points', postgresql_using='gist')
    op.drop_index(op.f('ix_run_gps_points_h3_cell_id'), table_name='run_gps_points')
    op.drop_table('run_gps_points')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_runs_validation_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_server_started_at'), table_name='runs')
    op.drop_index('ix_runs_route_gist', table_name='runs', postgresql_using='gist')
    op.drop_index(op.f('ix_runs_finished_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_device_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_xp_ledger_user_id'), table_name='xp_ledger')
    op.drop_table('xp_ledger')
    op.drop_index('ix_territories_owner_power', table_name='territories')
    op.drop_index(op.f('ix_territories_owner_id'), table_name='territories')
    op.drop_index(op.f('ix_territories_h3_resolution'), table_name='territories')
    op.drop_table('territories')
    op.drop_table('player_progress')
    op.drop_index(op.f('ix_leaderboard_scores_user_id'), table_name='leaderboard_scores')
    op.drop_index('ix_leaderboard_rank_lookup', table_name='leaderboard_scores')
    op.drop_table('leaderboard_scores')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_fingerprint_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_account_status'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
